### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages

### ISSUE THREAD

**Issue by Truemedia** [markusjwetzel/laravel-handlebars#1]
Hi there, I was trying to setup your repo when I got this error on running composer update.

zordius/lightncandy dev-master -> no matching package found

I believe altering the composer.json include line to
"zordius/lightncandy": "^0.20.0"

will fix this

**Comment by markusjwetzel** [comment]
Well, `dev-master` works for me. Anyway I have changed it to `"zordius/lightncandy": "0.*"`. Hope you can setup the repo now. :smiley:

**Comment by Truemedia** [comment]
Cheers that is working fine for me now, composer doesn't complain anymore :+1:
