### ISSUE TITLE
Last update broke using partials from template dir

### ISSUE THREAD

**Issue by vascopitaf** [markusjwetzel/laravel-handlebars#10]
hi there,

When updated lightncandy to v0.89, it only looks for partials in resources/views

I'm using pingpong modules

downgrading solved the issue, but latest laravel handlebars, requires lightncandy v0.89

**Comment by markusjwetzel** [comment]
Please use v1.0.1 for now (as you have already mentioned). I don't have time to fix this issue, so any pull requests to solve this issue are welcome. :)

**Comment by Lorti** [comment]
@vascopitaf, in the newest LightnCandy versions you have to provide a "partialresolver". The latest update of this package ( 1.2.0 ) lets you provide a partialresolver in the config file. If you don't it will look for partials in the view storage paths you have set.

Could you try 1.2.0 and tell us if the issue has been resolved?
