### ISSUE TITLE
Support for LightnCandy v0.94

### ISSUE THREAD

**Issue by Lorti** [markusjwetzel/laravel-handlebars#11]
Hi Markus,

do you plan on updating this package to use the latest LightnCandy? 
I have naively updated the version number in a fork and got some error messages. It seems that there have been some API changes since v0.89?

If you don't have the time I will look further into it and maybe open up a pull request.

Grüße aus Linz,
Manuel

**Comment by markusjwetzel** [comment]
Hi Manuel,

currently I don't have any plans to update this package, so pull requests are welcome. :)

Grüße aus Wien,
Markus

**Comment by Lorti** [comment]
Alright, thank you for the quick answer! 😀 
Already started to fix breaking changes starting with [v0.90](https://github.com/zordius/lightncandy/releases/tag/v0.90), there are quite a few.
