### ISSUE TITLE
View not found (with .hbs extension)

### ISSUE THREAD

**Issue by Truemedia** [markusjwetzel/laravel-handlebars#2]
Hi again, sorry just pointing out another small thing.

When I was trying to set this up and publish the config I originally got a view not found error.

Looking at the config I realize you have this line
'fileext' => [
        '.handlebars',
        '.hb',
    ],

Adding .hbs to this works but is the "hb" a typo or is that another file extension people use for handlebars? I know hbs and handlebars are used quite commonly as the extension.

**Comment by markusjwetzel** [comment]
Thanks for the hint! No, it was not a typo, I just did not know that `.hbs` is more common than `.hb`. I have changed the default config to `.hbs`. :+1:

**Comment by Truemedia** [comment]
Cheers :+1: 
By the way I am going to close down my simillar repo and contribute to this one since it has a lot more features compared to mine.

**Comment by markusjwetzel** [comment]
Thank you for using this package. We will use this package in a real project, so you can be sure that I will keep this package up to date. ☺
