### ISSUE TITLE
publish config

### ISSUE THREAD

**Issue by ftrotter** [markusjwetzel/laravel-handlebars#24]
You need to publish the config using

`php artisan vendor:publish --tag=config`

I do not see that in the readme, but its pretty important as you discuss configuration...

Esp since you do not get support for .mustache file without modifying that file... it would also be nice to support those out-of-the-gate.

**Comment by greut** [comment]
Apparently laravel can cache those (`php artisan config:clear`), renaming the configuration to `laravel-handlebars` can make the installation clearer for the future.

**Comment by Lorti** [comment]
@greut has fixed this in #25. The fix is available in [1.8.0](https://github.com/ProAI/laravel-handlebars/releases/tag/1.8.0).
