### ISSUE TITLE
Prevent caching if modified date is out

### ISSUE THREAD

**Issue by Truemedia** [markusjwetzel/laravel-handlebars#3]
Hi there,
I seem to be getting a lot of caching problems with my content. It is easy to fix but gets quite mundane to delete multiple files everytime you make a change to a template.

May I suggest implementing something where the modified dates of both the template and the cached file are compared and if the modified date of the template is newer than the cached file then the cache gets regenerated.

I have done this in laravel 5 before and would be willing to contribute code if needed.

**Comment by markusjwetzel** [comment]
I'm sorry, I haven't got your point yet. :worried:

The current implementation should regenerate a cached template whenever a template has been edited (i. e. if last modified date of template is greater than last modified date of cached template -> regenerate cached template).

Do you mean something else? Can you give me an example?

**Comment by Truemedia** [comment]
No that's exactly what I mean which is good, but it doesn't seem to do it for partials.

Anywhere I use {{> _partial}} always seems to be permanetly cached (no changes you make will ever show unless you delete the cache).

**Comment by markusjwetzel** [comment]
Now I got it, thank you! You are right, partials are not cached after an update for now.

Feel free to implement a solution for this problem and to create a pull request, which I can accept.

**Comment by Truemedia** [comment]
I'll give it a try, and yeh i'll do that if I can get a solution working.

**Comment by Truemedia** [comment]
Sorry I completely forgot about this project (it's been a year already wow). I am looking to do a lot of projects in Laravel with handlebars soon so I will pick this back up and possibly contribute to other functionality of you guys are still accepting pull requests ;)

**Comment by Lorti** [comment]
I have created a fix for this at #14. Could you please review the changes?
