### ISSUE TITLE
How to add a custom helper?

### ISSUE THREAD

**Issue by fesja** [markusjwetzel/laravel-handlebars#7]
Hi,

I'm quite lost on how to use the package with Laravel 5. I want to use the templates both in server and in client.
- I've created a helper called `hotness` in `/resources/views/helpers/hotness.js`. 
- I've added `'helpers' => ['hotness'],` to `/config/handlebars.php`.
- Then I use `{{hotness job.company.hotness }}` on my .hbs template

I have the following error:

```
ErrorException in lightncandy.php line 792:
Can not find custom helper function defination hotness() ! (View: /home/.../resources/views/job/list.blade.php)
```

What's wrong? Also, could you share a working example?

Thanks a lot!!

**Comment by fesja** [comment]
What I've done is write on `/config/handlebars.php`:

```
'helpers' => [
        'hotness' => function($args, $named) {
            ....
            return $html;
        }
    ],
```

But I'm sure that function could and should be in an external file. How?

My main problem now is, how can I use the handlebars templates (*.hbs) on javascript? Are you compiling them with Gulp and then saving them on files on the `/public` folder? How to achieve it? I've tried this [npm module](https://www.npmjs.com/package/laravel-elixir-handlebars) but it doesn't seem to work.

Sorry for so many questions, but I'm quite lost with no examples.

**Comment by markusjwetzel** [comment]
Hi fesja,

as you have figured out writing the function inside the config file is one way to add a custom helper. If you want to add a function from another file, you have to make sure to include this file before the code is executed.
Here you can see how this can be done: http://laravel-recipes.com/recipes/50/creating-a-helpers-file

If you want to use a handlebars template on client side, it is best practice to output the template inside a script tag, i. e.:

```
<script type="text/template" id="tpl-comment">
@raw('comment')
</script>
```

Then you can grab the template on client side with pure javascript, jQuery or whatever. Here is a tiny example with jQuery:

```
var html = $('#tpl-comment').html();
Handlebars.compile(html);
```

For more information about client side usage see http://handlebarsjs.com/.

**Comment by fesja** [comment]
thanks a lot Markus!

**Comment by PaulHendriks** [comment]
I'm trying to get this working... i have a helper function on the .JS -side of things, and a helper function in config/handlebars.php:

```    'helpers' => [
	    'ifCond' => function ($v1, $operator, $v2, $options) {
		    return true;
	    }
    ],
    'helperresolver' => true,
```

Not sure if helperresolver needs to be true in order to use helpers?

Anyway, the front end (.js) works, but PHP wont render the template, i get 

> Custom helper not found: ifCond in {{#ifCond this.sort \'==\' \'ASC\' }} !

Any thoughts?

**Comment by venturespace** [comment]
the function part has to be put in brackets:
```
	    'ifCond' => (function ($v1, $operator, $v2, $options) {
		    return true;
	    })
    ],
    'helperresolver' => true,
```

**Comment by PaulHendriks** [comment]
Thanks for the reply 👍 
I've tried your solution, but still get the same error.
Any thoughts?

**Comment by PaulHendriks** [comment]
OK... it's been a while.. i've run into this issue again and solved it by renaming 'helpers' to 'hbhelpers'.
I now have a PHP port of the same helper that i use in JS front end.
